apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoidWxyaWNoLXN1biIsInBhc3N3b3JkIjoiZ2hwX0lTMG5vS1EwSk9xY3ZOVlBYc2tQREVnYUEwQ3I2cTBib25wdSIsImF1dGgiOiJkV3h5YVdOb0xYTjFianBuYUhCZlNWTXdibTlMVVRCS1QzRmpkazVXVUZoemExQkVSV2RoUVRCRGNqWnhNR0p2Ym5CMSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
type: kubernetes.io/dockerconfigjson