{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.mysql.name }}
    {{- include "paymybuddy.mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.port }}
    protocol: TCP
    name: mysql
  selector:
    app: {{ .Values.mysql.name }}
    {{- include "paymybuddy.mysql.selectorLabels" . | nindent 4 }}
{{- end }}
