apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-service
  namespace: paymybuddy
spec:
  selector:
    app: paymybuddy
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
